out_dir : "."  # out dir
url_tag : "json" # web url tag(json,db(https://github.com/google/go-querystring))
language : "English"  # language(English,中 文)
db_tag : "gorm" # DB tag(gorm,db)
simple : false #simple output
is_out_sql : false # Whether to output sql
is_out_func : false # Whether to output function
is_foreign_key : false # Whether to mark foreign key or not
is_gui : false # Whether to operate on gui
is_table_name : true # Whether to out GetTableName/column function
is_null_to_point : false # database is 'DEFAULT NULL' then set element type as point
is_web_tag: true # json tag
is_web_tag_pk_hidden: false  # json tag 隐藏主键
web_tag_type: 1 # json tag 0: Small Camel-Case 1: _
table_prefix: "" #table prefix
is_column_name: true # Whether to generate column names
is_out_file_by_table_name: true # Whether to generate multiple models based on table names
self_type_define: # Custom data type mapping
    float: float64
    tinyint(1): int64
db_info :
    host : "127.0.0.1"
    port : 3306
    username : "root"
    password : "cx654321"
    database : "test"
    type: 0 # database type (0:mysql , 1:sqlite , 2:mssql)
table_names: "t_users" # Specified table generation, multiple tables with , separated
out_file_name: "t_users" # Custom build file name
