# 测试环境配置

redis:
  host: "127.0.0.1"
  port: 6379
  auth: ""
  index:
    cache: 4     # 缓存
    storage: 5   # 存储
    jwt: 6       # JWT

jwtSecret: "Xx4KJQ2AguFL5gWurcRJvVfDC5a2itLi53vFJN9wthYkrxtQbdeRDkWTHzAjnn5n"